<?php
return [
    'inicio' => ['controller' => 'HomeController', 'method' => 'index'],
    'inventario' => ['controller' => 'InventarioController', 'method' => 'index'],
    'inventario/guardar' => ['controller' => 'InventarioController', 'method' => 'guardar'],
    'inventario/eliminar' => ['controller' => 'InventarioController', 'method' => 'eliminar'],
    'usuarios' => ['controller' => 'UsuarioController', 'method' => 'index'],
    'usuarios/guardar' => ['controller' => 'UsuarioController', 'method' => 'guardar'],
    'usuarios/eliminar' => ['controller' => 'UsuarioController', 'method' => 'eliminar'], 
    'roles' => ['controller' => 'RolController', 'method' => 'index'],
    'roles/guardar' => ['controller' => 'RolController', 'method' => 'guardar'],
    'roles/eliminar' => ['controller' => 'RolController', 'method' => 'eliminar'],
    'opciones' => ['controller' => 'OpcionController', 'method' => 'index'],
    'opciones/guardar' => ['controller' => 'OpcionController', 'method' => 'guardar'],
    'opciones/eliminar' => ['controller' => 'OpcionController', 'method' => 'eliminar'],
    'permisos' => ['controller' => 'PermisoController', 'method' => 'index'],
    'permisos/guardar' => ['controller' => 'PermisoController', 'method' => 'guardar'],
    'proveedores' => ['controller' => 'ProveedorController', 'method' => 'index'],
    'proveedores/guardar' => ['controller' => 'ProveedorController', 'method' => 'guardar'],
    'proveedores/eliminar' => ['controller' => 'ProveedorController', 'method' => 'eliminar'],
    'clientes' => ['controller' => 'ClienteController', 'method' => 'index'],
    'clientes/guardar' => ['controller' => 'ClienteController', 'method' => 'guardar'],
    'clientes/eliminar' => ['controller' => 'ClienteController', 'method' => 'eliminar'],
    'ventas'         => ['controller' => 'VentaController', 'method' => 'index'],
    'ventas/guardar' => ['controller' => 'VentaController', 'method' => 'guardar'],
    'ubicaciones' => ['controller' => 'UbicacionController', 'method' => 'index'],
    'ubicaciones/getMunicipios' => ['controller' => 'UbicacionController', 'method' => 'getMunicipios'],
    'ubicaciones/getDistritos'  => ['controller' => 'UbicacionController', 'method' => 'getDistritos'],
    'ubicaciones/eliminarDepto' => ['controller' => 'UbicacionController', 'method' => 'eliminarDepto'],
    'ubicaciones/guardarDepto' => ['controller' => 'UbicacionController', 'method' => 'guardarDepto'],
    'ubicaciones/guardarMuni'  => ['controller' => 'UbicacionController', 'method' => 'guardarMuni'],
    'ubicaciones/guardarDist'  => ['controller' => 'UbicacionController', 'method' => 'guardarDist'],
    'sucursales'          => ['controller' => 'SucursalController', 'method' => 'index'],
    'sucursales/guardar'  => ['controller' => 'SucursalController', 'method' => 'guardar'],
    'sucursales/eliminar' => ['controller' => 'SucursalController', 'method' => 'eliminar'],
    'ventas/imprimir' => ['controller' => 'VentaController', 'method' => 'imprimir'],
    'productos' => ['controller' => 'ProductoController', 'method' => 'index'],
    'productos/guardar' => ['controller' => 'ProductoController', 'method' => 'guardar'],
    'login'  => ['controller' => 'AuthController', 'method' => 'login'],
    'logout' => ['controller' => 'AuthController', 'method' => 'logout'],
    'usuarios/crear'   => ['controller' => 'UsuarioController', 'method' => 'crear'],
    'usuarios/guardar' => ['controller' => 'UsuarioController', 'method' => 'guardar'],
    'usuarios/editar'  => ['controller' => 'UsuarioController', 'method' => 'editar'],
    'usuarios/eliminar'=> ['controller' => 'UsuarioController', 'method' => 'eliminar'],
];